#ifndef SEARCHFOLDERLIBRARY_GLOBAL_H
#define SEARCHFOLDERLIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SEARCHFOLDERLIBRARY_LIBRARY)
#  define SEARCHFOLDERLIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define SEARCHFOLDERLIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // SEARCHFOLDERLIBRARY_GLOBAL_H
